// Core type definitions - export specific types to avoid conflicts
// Export common types first (base types)
export * from './common';

// Export domain-specific types with potential conflicts handled
export type { 
  // Auth types
  User,
  AuthProvider,
  LoginInput,
  RegisterInput,
  ForgotPasswordInput,
  ResetPasswordInput,
  VerifyEmailInput,
  OAuthConfig,
  SecurityEvent,
  Permission,
  Role
} from './auth';

export type {
  // Wallet types (renamed to avoid conflicts)
  WalletDateRange,
  WalletType,
  TransactionType,
  TransactionStatus,
  TransactionDirection,
  BankFilterType,
  PaymentMethodFilterType,
  SortByType,
  SortOrderType,
  DateFilterType,
  Amount,
  Currency,
  Country,
  Bank,
  PaymentMethod,
  Wallet,
  Transaction,
  TransactionSummary,
  TransactionFilters,
  CreateWalletInput,
  UpdateWalletInput,
  CreateTransactionInput,
  UpdateTransactionInput,
  CreateBankInput,
  UpdateBankInput,
  CreatePaymentMethodInput,
  UpdatePaymentMethodInput
} from './wallet';

export type {
  // Calendar types
  CalendarEvent,
  Calendar,
  EventAttendee,
  EventOrganizer,
  EventReminder,
  EventAttachment,
  RecurrenceRule,
  CalendarSettings,
  WorkingHours,
  CalendarShareSettings,
  CalendarShare,
  CalendarPermissions,
  CalendarPermission,
  GoogleCalendarSync,
  CalendarSyncSettings,
  CreateEventInput,
  UpdateEventInput,
  CreateCalendarInput,
  UpdateCalendarInput,
  ShareCalendarInput,
  EventFilter,
  CalendarFilter,
  EventResponse,
  CalendarResponse,
  EventsResponse,
  CalendarsResponse
} from './calendar';

export type {
  // API types
  ApiRequest,
  ApiResponse,
  ApiError,
  PaginationParams,
  PaginationResponse,
  FilterParams,
  SortParams,
  SearchParams,
  HttpMethod,
  HttpStatus,
  ApiVersion,
  RateLimitType,
  CacheControl,
  ContentType
} from './api';

export type {
  // UI types
  ComponentProps,
  ResponsiveValue,
  AnimationConfig,
  TransitionConfig,
  AriaProps,
  LocaleConfig,
  LazyLoadConfig,
  VirtualScrollConfig,
  ErrorBoundaryState,
  ErrorFallbackProps,
  ThemeContextType,
  AuthContextType,
  UseLocalStorageReturn,
  UseDebounceReturn,
  UseIntersectionObserverReturn,
  UseClickOutsideReturn,
  UseHoverReturn,
  UseKeyPressReturn,
  UseMediaQueryReturn,
  KeyboardEventHandler,
  MouseEventHandler,
  ChangeEventHandler,
  FocusEventHandler,
  FormEventHandler,
  RefCallback,
  RefObject,
  ReactNode,
  ReactElement,
  ReactChild,
  ReactChildren,
  CSSProperties,
  CSSClassName,
  CSSVariable,
  CSSColor,
  CSSSize,
  CSSSpacing,
  LayoutDirection,
  FlexDirection,
  JustifyContent,
  AlignItems,
  Position,
  Display,
  GridTemplate,
  GridArea,
  GridGap,
  ZIndex,
  BorderRadius,
  BorderWidth,
  BorderStyle,
  BorderColor,
  BoxShadow,
  TextShadow,
  FontFamily,
  FontSize,
  FontWeight,
  LineHeight,
  TextAlign,
  TextTransform,
  TextDecoration,
  Margin,
  Padding,
  Gap,
  Width,
  Height,
  MinWidth,
  MaxWidth,
  MinHeight,
  MaxHeight,
  Overflow,
  Cursor,
  UserSelect,
  PointerEvents,
  Transform,
  TransformOrigin,
  TransitionProperty,
  TransitionDuration,
  TransitionTimingFunction,
  TransitionDelay,
  AnimationName,
  AnimationDuration,
  AnimationTimingFunction,
  AnimationDelay,
  AnimationIterationCount,
  AnimationDirection,
  AnimationFillMode,
  AnimationPlayState
} from './ui';